import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "p1",
    slug: "premium-cast-iron-skillet",
    name: "Iron Spatula",
    price: 5000.0,
    category: "Cookware",
    description:
      "Hand-forged iron spatula with a long, sturdy handle and a wide, flat blade. Perfect for flipping, sautéing, and scraping in cast iron skillets and griddles.",
    image: "/images/utensils/iron-spatula.png",
    rating: 4.8,
    reviewCount: 312,
    badge: "Sale",
    inStock: true,
  },
  {
    id: "p2",
    slug: "chefs-knife",
    name: "Chef's Knife",
    price: 10000.0,
    category: "Knives",
    description:
      "Crafted from high-carbon German steel, this 8-inch chef's knife features an ergonomic handle and a precision-honed blade that stays sharper for longer. A kitchen workhorse.",
    image: "/images/utensils/k9.jpeg",
    rating: 4.9,
    reviewCount: 184,
    badge: "Popular",
    inStock: true,
  },
  {
    id: "p3",
    slug: "copper-cookware-set-10pc",
    name: "Copper Cookware Set (6-Piece)",
    price: 15000.0,
    category: "Cookware",
    description:
      "Elegant 6-piece professional copper cookware set. Offers unmatched heat responsiveness and precise control for delicate sauces, sautés, and braises. Includes lids.",
    image: "/images/utensils/k4.jpeg",
    rating: 4.7,
    reviewCount: 95,
    badge: "Premium",
    inStock: true,
  },
  {
    id: "p4",
    slug: "plates-bowls-set",
    name: "Stoneware Plates & Bowls Set",
    price: 15000,
    category: "Tableware",
    description:
      "Set of 4 handcrafted stoneware dinner plates and bowls in a beautiful speckled glaze. Durable, microwave and dishwasher safe, and perfect for everyday use or special occasions.",
    image: "/images/utensils/saucepan.png",
    rating: 4.6,
    reviewCount: 220,
    inStock: true,
  },
  {
    id: "p5",
    slug: "tabletop-tray-set",
    name: "Elegant Tabletop Tray Set",
    price: 3000.0,
    category: "Tableware",
    description:
      "Set of 3 elegant serving trays in varying sizes, crafted from durable bamboo with a natural finish. Perfect for serving appetizers, cheese, charcuterie, or as stylish catch-alls on your countertop.",
    image: "/images/utensils/k8.jpeg",
    rating: 4.9,
    reviewCount: 412,
    badge: "New",
    inStock: true,
  },
  {
    id: "p6",
    slug: "golden-spoon-ladle-set",
    name: "Golden Spoon & Ladle Set",
    price: 39.99,
    category: "Tableware",
    description:
      "Elegant set of 2 golden spoons and a ladle, crafted from high-quality stainless steel. Perfect for serving soups, stews, and other liquid dishes.",
    image: "/images/utensils/k10.jpeg",
    rating: 4.5,
    reviewCount: 148,
    inStock: true,
  },
  {
    id: "p7",
    slug: "ceramic-bowls-set",
    name: "Ceramic Bowls Set",
    price: 45.0,
    category: "Tableware",
    description:
      "Set of 4 handcrafted ceramic bowls in a beautiful speckled glaze. Durable, microwave and dishwasher safe, and perfect for everyday use or special occasions.",
    image: "/images/utensils/k13.jpeg",
    rating: 4.7,
    reviewCount: 88,
    inStock: true,
  },
  {
    id: "p8",
    slug: "plate-rack-organizer",
    name: "Plate Rack Organizer",
    price: 99.0,
    originalPrice: 120.0,
    category: "Appliances",
    description:
      "Sturdy metal plate rack organizer with a sleek black finish. Features adjustable dividers to securely hold plates, bowls, and cutting boards while maximizing vertical storage space in your kitchen.",
    image: "/images/utensils/k2.jpeg",
    rating: 4.8,
    reviewCount: 167,
    badge: "Sale",
    inStock: true,
  },
  {
    id: "p9",
    slug: "spoon-rest-set",
    name: "Spoon Rest Set",
    price: 55.0,
    category: "Tools",
    description: "Elegant set of wooden spoon rests to keep them sharp.",
    image: "/images/utensils/k1.jpeg",
    rating: 4.9,
    reviewCount: 204,
    badge: "Popular",
    inStock: true,
  },
  {
    id: "p10",
    slug: "knives-set",
    name: "Premium Knife Set",
    price: 199.99,
    category: "Knives",
    description:
      "Complete set of high-quality kitchen knives with ergonomic handles and sharp, durable blades. Perfect for all your cutting needs.",
    image: "/images/utensils/k5.jpeg",
    rating: 4.8,
    reviewCount: 156,
    badge: "Premium",
    inStock: true,
  },
  {
    id: "p11",
    slug: "professional-stand-mixer",
    name: "Professional Kitchen Stand Mixer",
    price: 6000,
    category: "Bakeware",
    description:
      "High-performance kitchen stand mixer with 5-quart bowl and 10 speed settings. Effortlessly mix bread dough, cake batter, meringue, and more. Attachments included.",
    image:
      "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&w=600&q=80",
    rating: 4.9,
    reviewCount: 524,
    badge: "New",
    inStock: true,
  },
  {
    id: "p12",
    slug: "colored-plates-set",
    name: "Colored Plates Set",
    price: 7000,
    category: "Tableware",
    description:
      "Set of 6 vibrant colored plates, perfect for adding a pop of color to any dining table.",
    image: "/images/utensils/k15.jpeg",
    rating: 4.6,
    reviewCount: 190,
    inStock: true,
  },
  {
    id: "p13",
    slug: "plates-set",
    name: "Plates Set",
    price: 9000,
    category: "Tableware",
    description:
      "Set of 6 vibrant colored plates, perfect for adding a pop of color to any dining table.",
    image: "/images/utensils/k14.jpeg",
    rating: 4.6,
    reviewCount: 190,
    inStock: true,
  },
  {
    id: "p14",
    slug: "electric-kettle",
    name: "Electric Kettle",
    price: 12000,
    category: "Appliances",
    description:
      "Fast-boiling electric kettle with a sleek design and safety features.",
    image: "/images/utensils/k18.jpeg",
    rating: 4.6,
    reviewCount: 190,
    inStock: true,
  },
  {
    id: "p15",
    slug: "pot-set",
    name: "Pot Set",
    price: 10000,
    category: "Cookware",
    description: "Set of 6 pots with lids, perfect for all your cooking needs.",
    image: "/images/utensils/k17.jpeg",
    rating: 4.6,
    reviewCount: 190,
    inStock: true,
  },
  {
    id: "p16",
    slug: "serving-pot",
    name: "Serving Pot",
    price: 17000,
    category: "Cookware",
    description:
      "Beautiful serving pot perfect for bringing dishes to the table.",
    image: "/images/utensils/k16.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
  {
    id: "p17",
    slug: "eating-utensils-set",
    name: "Eating Utensils Set",
    price: 10000,
    category: "Tableware",
    description:
      "Universal set of eating utensils perfect for all your dining needs.",
    image: "/images/utensils/k19.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
  {
    id: "p18",
    slug: "Utensils-rack",
    name: "Utensils Rack",
    price: 8000,
    category: "Tableware",
    description:
      "Beautiful utensils rack perfect for organizing your kitchen tools and keeping them within easy reach.",
    image: "/images/utensils/k20.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
  {
    id: "p19",
    slug: "cutlery-set",
    name: "Cutlery Set",
    price: 5000,
    category: "Tableware",
    description: "Universal set of cutlery perfect for all your dining needs.",
    image: "/images/utensils/k21.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
  {
    id: "p20",
    slug: "knives-set-with-rack",
    name: "Knives Set with Rack",
    price: 10000,
    category: "Knives",
    description:
      "Complete set of knives with a convenient rack for easy storage and organization.",
    image: "/images/utensils/k22.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
  {
    id: "p21",
    slug: "pot-set",
    name: "Pot Set",
    price: 20000,
    category: "Cookware",
    description:
      "Beautiful pot set perfect for all your cooking needs, featuring a variety of sizes and a sleek design that complements any kitchen decor.",
    image: "/images/utensils/k23.jpeg",
    rating: 4.6,
    reviewCount: 190,
    badge: "New",
    inStock: true,
  },
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug);
};

export const getRelatedProducts = (product: Product, limit = 4): Product[] => {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || p.inStock))
    .slice(0, limit);
};
